name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test the docker image
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ./gha/action.yml
      id: hello
