name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test the docker image
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ./.github/actions
      id: hello
      run: |
        bash build.sh
        bash run_example.sh
